/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import java.awt.Font;
import java.util.logging.Level;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author cleefsouza
 */

public class Glasgow extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Glasgow() {
        initComponents();
        this.setLocationRelativeTo(null); // Inicia a frame no centro da tela
        UIManager.put("OptionPane.messageFont", new Font("Century Gothic", Font.BOLD, 12)); // Alterando a fonte
    }

    public int ocularPontuacao() { // Metodo que retorna a pontuação ocular
        int ocu = 0;
        if (ocularCombo.getSelectedIndex() == 0) {
            ocu = 4;
        } else if (ocularCombo.getSelectedIndex() == 1) {
            ocu = 3;
        } else if (ocularCombo.getSelectedIndex() == 2) {
            ocu = 2;
        } else if (ocularCombo.getSelectedIndex() == 3) {
            ocu = 1;
        }
        System.out.println("Pontuação Ocular: " + ocu);
        return ocu;
    }

    public int verbalPontuacao() {  // Metodo que retorna a pontuação verbal
        int ver = 0;
        if (verbalCombo.getSelectedIndex() == 0) {
            ver = 5;
        } else if (verbalCombo.getSelectedIndex() == 1) {
            ver = 4;
        } else if (verbalCombo.getSelectedIndex() == 2) {
            ver = 3;
        } else if (verbalCombo.getSelectedIndex() == 3) {
            ver = 2;
        } else if (verbalCombo.getSelectedIndex() == 4) {
            ver = 1;
        }
        System.out.println("Pontuação Verbal: " + ver);
        return ver;
    }

    public int motoraPontuacao() {  // Metodo que retorna a pontuação motora
        int mot = 0;
        if (motoraCombo.getSelectedIndex() == 0) {
            mot = 6;
        } else if (motoraCombo.getSelectedIndex() == 1) {
            mot = 5;
        } else if (motoraCombo.getSelectedIndex() == 2) {
            mot = 4;
        } else if (motoraCombo.getSelectedIndex() == 3) {
            mot = 3;
        } else if (motoraCombo.getSelectedIndex() == 4) {
            mot = 2;
        } else if (motoraCombo.getSelectedIndex() == 5) {
            mot = 1;
        }
        System.out.println("Pontuação Motora: " + mot);
        return mot;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sairButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        verbalCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ocularCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        motoraCombo = new javax.swing.JComboBox<>();
        resultadoButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Desenvolvedor: Aryosvalldo Cleef de Souza");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Matricula: 1720020786");

        sairButton.setBackground(new java.awt.Color(255, 204, 204));
        sairButton.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        sairButton.setText("Sair");
        sairButton.setToolTipText("Encerrar Aplicação");
        sairButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sairButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel26.setText("Abertura Ocular - AO");

        verbalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NV 5 - Orientado e Conversando ", "NV 4 - Confuso", "NV 3 - Fala Aleatória", "NV 2 - Sons Incompreensíveis", "NV 1 - Sem Resposta Verbal" }));
        verbalCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Resposta Verbal - RV");

        ocularCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NV 4 - Espontânea", "NV 3 - Comando Verbal", "NV 2 - À Dor", "NV 1 - Sem Resposta Ocular" }));
        ocularCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Resposta Motora - RM");

        motoraCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NV 6 - Obedece Comandos", "NV 5 - Localiza Estimulo Doloros", "NV 4 - Retirada Inesperada à Dor", "NV 3 - Padrão Flexor à Dor [decorticação]", "NV 2 - Padrão Extensor à Dor [descerebração]", "NV 1 - Sem Resposta Motora" }));
        motoraCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        resultadoButton.setBackground(new java.awt.Color(201, 226, 251));
        resultadoButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        resultadoButton.setText("Resultado");
        resultadoButton.setToolTipText("Calcular Pontuação");
        resultadoButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resultadoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resultadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoButtonActionPerformed(evt);
            }
        });

        infoButton.setBackground(new java.awt.Color(255, 255, 204));
        infoButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        infoButton.setText("Informações");
        infoButton.setToolTipText("Saiba Mais");
        infoButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        infoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoButton.setMaximumSize(new java.awt.Dimension(59, 18));
        infoButton.setMinimumSize(new java.awt.Dimension(59, 18));
        infoButton.setPreferredSize(new java.awt.Dimension(59, 18));
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(ocularCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verbalCombo, 0, 242, Short.MAX_VALUE)
                    .addComponent(motoraCombo, 0, 1, Short.MAX_VALUE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocularCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(verbalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(resultadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motoraCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("Nome");
        jLabel3.getAccessibleContext().setAccessibleName("Matricula");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Escala de Coma de Glasgow");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // Finalizar a aplicação
        int sairButton = JOptionPane.showConfirmDialog(null, "Deseja sair realmente?", "Sair", JOptionPane.YES_NO_OPTION);
        if (sairButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_sairButtonActionPerformed

    private void resultadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoButtonActionPerformed

        int pontuacao = (ocularPontuacao() + verbalPontuacao() + motoraPontuacao()); // Pontuação total
        System.out.println("Pontuação Total: "+pontuacao);
        
        // Validando resultados em tela
        if (pontuacao <= 8) {
            JOptionPane.showMessageDialog(null, "Resultado Avaliação [ECG]\n"
                    + "Pontuação Total: " + pontuacao + "\n"
                    + "Situação do Paciente: GRAVE\n"
                    + "[Necessidade de Intubação Imediata]", "Resultado", JOptionPane.ERROR_MESSAGE);
        } else if (pontuacao <= 12) {
            JOptionPane.showMessageDialog(null, "Resultado Avaliação [ECG]\n"
                    + "Pontuação Total: " + pontuacao + "\n"
                    + "Situação do Paciente: MODERADO\n", "Resultado", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Resultado Avaliação [ECG]\n"
                    + "Pontuação Total: " + pontuacao + "\n"
                    + "Situação do Paciente: LEVE\n", "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_resultadoButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        // Chama um pane com explicações sobre a pontuação total na escala de glasgow
        JOptionPane.showMessageDialog(null, "¬ Pontuação total: de 3 a 15\n"
                + "3 = Coma profundo. [85% de probabilidade de morte; estado vegetativo]\n"
                + "4 = Coma profundo.\n"
                + "7 = Coma intermediário.\n"
                + "11 = Coma superficial.\n"
                + "15 = Normalidade.\n"
                + "-------------------------------------------------------------------------------------\n"
                + "¬ Classificação do Trauma cranioencefálico [ATLS, 2005]\n"
                + "3-8 = Grave. [necessidade de intubação imediata]\n"
                + "9-12 = Moderado.\n"
                + "13-15 = Leve."
                + "", "Informações", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_infoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glasgow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glasgow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glasgow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glasgow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Glasgow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> motoraCombo;
    private javax.swing.JComboBox<String> ocularCombo;
    private javax.swing.JButton resultadoButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JComboBox<String> verbalCombo;
    // End of variables declaration//GEN-END:variables
}
